### ISSUE TITLE
Seeking more details about the runtime_distribution and rt_list 

### ISSUE THREAD

**Issue by AltafAllahAbbassi** [Elfsong/Venus#1]
Hi 
Thank you for your great work. 
I have questions regarding the dataset. 

Question 1: 
What does it represent ["124", "0.125"] in runtime distribution. I suppose that the second number is a measure but what for the first number. 

Question 2: 
I supposed that the first number is the id of the submission, but there some id that I can't find in rt_list. 

Thank you for your time.

**Comment by Elfsong** [comment]
Hi @AltafAllahAbbassi Thank you for asking:)

> Question 1:
> What does it represent ["124", "0.125"] in runtime distribution. I suppose that the second number is a measure but what for the first number.

The first number is the running time measurement in milliseconds, and the second number is the runtime percentage.

> Question 2:
> I supposed that the first number is the id of the submission, but there some id that I can't find in rt_list.

We didn't collect the submission ID.

**Comment by AltafAllahAbbassi** [comment]
Thank for your response. 

A follow up question: is there a way to map a specific code from rt_list to its respective runtime distribution or vice versa ?

**Comment by Elfsong** [comment]
> A follow up question: is there a way to map a specific code from rt_list to its respective runtime distribution or vice versa ?

If you need to find a specific solution that runs at an exact time, you can refer to the 'runtime' field in each solution instance within the "rt_list".

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/51ec4e00-cc09-45bd-aec0-a7ffb67139d5">

**Comment by AltafAllahAbbassi** [comment]
thank you for your informative answers.

**Comment by Elfsong** [comment]
@AltafAllahAbbassi Please feel free to reopen it if you have further questions. Thank you!
